; This is your customizable slap configuration. Defaults are located here:
; https://github.com/justadropofwater/slap/blob/master/slap.ini
; https://github.com/justadropofwater/editor-widget/blob/main/editor-widget.ini
; https://github.com/slap-editor/slap-clipboard-plugin/blob/master/slap-clipboard-plugin.ini

[logger]
level = "info"
